// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5mNjXEh9L9Njuc9_g35zSoTFHJRSIYZw',
    appId: '1:316326972081:web:8f8f27df170e2dde417090',
    messagingSenderId: '316326972081',
    projectId: 'testmassage-30973',
    authDomain: 'testmassage-30973.firebaseapp.com',
    storageBucket: 'testmassage-30973.appspot.com',
    measurementId: 'G-Z1E7GV9W5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDt6a9ahocxzIRcmvPHzh6x2f7PP4uisE',
    appId: '1:316326972081:android:aacf32f9c4e0d620417090',
    messagingSenderId: '316326972081',
    projectId: 'testmassage-30973',
    storageBucket: 'testmassage-30973.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKRijFgRstNmJ5VRHaktH1hm8mgmeqxXw',
    appId: '1:316326972081:ios:c7aa7a9526f8d81f417090',
    messagingSenderId: '316326972081',
    projectId: 'testmassage-30973',
    storageBucket: 'testmassage-30973.appspot.com',
    iosBundleId: 'com.example.uitraning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKRijFgRstNmJ5VRHaktH1hm8mgmeqxXw',
    appId: '1:316326972081:ios:c7aa7a9526f8d81f417090',
    messagingSenderId: '316326972081',
    projectId: 'testmassage-30973',
    storageBucket: 'testmassage-30973.appspot.com',
    iosBundleId: 'com.example.uitraning',
  );
}
